### ISSUE TITLE
Disallowed MIME type after upgrade to latest version

### ISSUE THREAD

**Issue by philvessey** [EdCharbeneau/BlazorSize#73] opened 2022-02-10 19:06 UTC
Hi

Upgraded package to 6.1.1 and now get this error in the console - no other change in the code from 6.1.0

_content/BlazorPro.BlazorSize/blazorSizeMediaModule.js was blocked because of a disallowed MIME type (“text/html”)

Has something changed that has caused this?

**Comment by EdCharbeneau** [comment] 2022-02-11 02:36
Can you please post the full error and your configuration: .NET version, Program.cs and index.html/cshtml

BlazorSize is tested end to end which includes a check during each testing phase for console errors. No such errors are happening in e2e.

Thanks

**Comment by Rikshy** [comment] 2022-02-11 16:01
Hi 

I also receive a similar error. TBF: I just rolled out the first version with blazorSize, previously I only used it on my LM.
Here is the error from my Browser: (I know for me it doesn't show any MIME type)
![grafik](https://user-images.githubusercontent.com/6615662/153624354-04559fd5-f9d0-49f2-b56a-cb75a57e0c51.png)

I am using .NET 6.0
[Program.cs](https://pastebin.com/1EgFpbWE)

Thanks, and sorry if this doesn't fit here

**Comment by philvessey** [comment] 2022-02-11 19:14
Here is the information - safari reports it as 404, Firefox as invalid mime type.
If rollback to 6.1.0 everything works fine - just bumping to 6.1.1 results in error with no other code changes.

<img width="1791" alt="error" src="https://user-images.githubusercontent.com/814882/153654426-894d14a6-8ab5-4897-82bc-f33cc6c4d299.png">

<img width="899" alt="index" src="https://user-images.githubusercontent.com/814882/153654798-44cc4918-98c4-4049-9604-8fbabc904483.png">

<img width="1235" alt="program" src="https://user-images.githubusercontent.com/814882/153654947-c1697781-a210-452c-979c-331f74af2f17.png">

**Comment by EdCharbeneau** [comment] 2022-02-12 01:37
Thanks for the extra details. I will try to reproduce this and issue a fix.

**Comment by philvessey** [comment] 2022-02-12 07:34
@EdCharbeneau blazor wasm on net6.0 against sdk 6.0.1 and tried 6.0.2

It happens both locally and on a deploy to azure static web apps.

**Comment by EdCharbeneau** [comment] 2022-02-12 14:31
@philvessey I've tried creating every variety of Blazor project using two different machines. I can't seem to reproduce this.

I noticed your index file uses both `_framework/blazor.webassembly.js` and the TagHelper `<component ...>`.

I'm not sure what type of project this is.

Also, can you try clearing your `/bin` and `/obj` folders? There could be something cached in here causing issues.

I'm still working on the issue, just running out of potential problems.

**Comment by philvessey** [comment] 2022-02-12 15:01
@EdCharbeneau sounds like something my end then - I'll see if I can get it going with a simple dotnet new and go from there - I'll report back.

Puzzled a bit why previous version works - would there be a caching issue on static web apps as it takes down the staging each time?

**Comment by EdCharbeneau** [comment] 2022-02-12 15:28
"Puzzled a bit why previous version works - would there be a caching issue on static web apps as it takes down the staging each time?"

Doesn't make sense to me either. 

There were hardly any changes to the codebase this update. I removed some log statements and updated two event handlers. Nothing that could be related IMO

**Comment by philvessey** [comment] 2022-02-12 15:59
@EdCharbeneau somethings not right - I get the same error on a vanilla dotnet new blazorwasm project. All I did here was add the package, add builder.Services.AddMediaQueryService(); to program cs and then wrap <MediaQueryList> to the Index.razor - and I get the error below.

<img width="1787" alt="Screenshot 2022-02-12 at 15 55 48" src="https://user-images.githubusercontent.com/814882/153718332-ea19a276-28ca-47d5-b3c1-53c48c92f6b7.png">

**Comment by philvessey** [comment] 2022-02-12 16:05
@EdCharbeneau on above when I change to 6.1.0 - no issue and everything good again.

**Comment by EdCharbeneau** [comment] 2022-02-12 19:23
Windows, Linux, or Mac?

Maybe there's a file name convention or something breaking it. I'm on Windows, maybe that's why I don't see it?

**Comment by philvessey** [comment] 2022-02-12 19:26
I'm Mac locally - guessing static web app is Linux?

**Comment by philvessey** [comment] 2022-02-12 19:42
I notice in the scripts folder there are two files for the media module - one has capital B, other lowercase - is this causing it do you think as the console error suggests its trying to load the lower case one.

<img width="353" alt="Screenshot 2022-02-12 at 19 40 28" src="https://user-images.githubusercontent.com/814882/153725900-d4451564-a23f-464e-b9ed-b321fadc800f.png">

**Comment by EdCharbeneau** [comment] 2022-02-12 19:47
This is probably it. I thought I fixed this before, there must have been a regression when I merged some branches.

I'll post a prerelease build shortly for you to test. Yay Linux Vs. NTFS

**Comment by philvessey** [comment] 2022-02-12 20:06
The worse kind of issues 😔

**Comment by EdCharbeneau** [comment] 2022-02-12 20:09
@philvessey Please enable pre-release packages and update to 6.1.22-pre. If this fixes your issue I'll create a full release. https://www.nuget.org/packages/BlazorPro.BlazorSize/6.1.22-pre

**Comment by EdCharbeneau** [comment] 2022-02-12 20:10
> The worse kind of issues

Especially when you fix them but Git seems to keep the old file name, because case is not a "change you can commit". I had to remove it, commit it, then add it back, commit again. 😡

**Comment by philvessey** [comment] 2022-02-12 20:14
@EdCharbeneau pre-release version is good to go - issue fixed ☺️

**Closed** 2022-02-12 20:19 UTC

**Comment by EdCharbeneau** [comment] 2022-02-12 20:21
Fixed with 6.1.2 https://www.nuget.org/packages/BlazorPro.BlazorSize/6.1.2

Thanks for submitting and working through this patiently 🍻
