### ISSUE TITLE
Intermittent Exceptions

### ISSUE THREAD

**Issue by Mike-E-angelo** [EdCharbeneau/BlazorSize#82] opened 2022-09-05 22:06 UTC
Greetings,

This component is working really well for me, thank you again for taking the time to develop it.  I do appear to be getting some intermittent exceptions, however, and was hoping to track them down.

To start, there's this one that I was getting earlier today, which I have not seen until then:
Added new issue: https://github.com/EdCharbeneau/BlazorSize/issues/91
```
Microsoft.JSInterop.JSException: Importing a module script failed.
undefined
   at async ValueTask<TValue> Microsoft.JSInterop.JSRuntime.InvokeAsync<TValue>(long targetInstanceId, string identifier, object[] args)
   at async Task BlazorPro.BlazorSize.MediaQueryService.CreateMediaQueryList(DotNetObjectReference<MediaQueryList> dotNetObjectReference)
   at async Task BlazorPro.BlazorSize.MediaQueryList.OnAfterRenderAsync(bool firstRender)
   at async Task Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
```

Additionally, I have also seen this one as well:
Added new issue: https://github.com/EdCharbeneau/BlazorSize/issues/90
```
Microsoft.JSInterop.JSDisconnectedException: JavaScript interop calls cannot be issued at this time. This is because the circuit has disconnected and is being disposed.
   at void Microsoft.AspNetCore.Components.Server.Circuits.RemoteJSRuntime.BeginInvokeJS(long asyncHandle, string identifier, string argsJson, JSCallResultType resultType, long targetInstanceId)
   at ValueTask<TValue> Microsoft.JSInterop.JSRuntime.InvokeAsync<TValue>(long targetInstanceId, string identifier, CancellationToken cancellationToken, object[] args)
   at async ValueTask<TValue> Microsoft.JSInterop.JSRuntime.InvokeAsync<TValue>(long targetInstanceId, string identifier, object[] args)
   at async ValueTask Microsoft.JSInterop.JSObjectReferenceExtensions.InvokeVoidAsync(IJSObjectReference jsObjectReference, string identifier, params object[] args)
   at async Task BlazorPro.BlazorSize.MediaQueryService.RemoveQuery(MediaQuery mediaQuery)
   at async Task BlazorPro.BlazorSize.MediaQueryList.RemoveQuery(MediaQuery mediaQuery)
   at async ValueTask BlazorPro.BlazorSize.MediaQuery.DisposeAsync()
   at async void Microsoft.AspNetCore.Components.RenderTree.Renderer.Dispose(bool disposing)+HandleAsyncExceptions(?)
```

No worries if they cannot be addressed.  I wanted to report them and see if there is a best practice I am overlooking and/or if this is something that can indeed be addressed on your side.

Thank you for any consideration/assistance you can provide.

**Comment by EdCharbeneau** [comment] 2022-09-06 14:15
Thanks for reporting this. I can check and see if there's something that can be done with JS runtime to prevent issues with (Blazor Server).

Is this happening at a specific time in the components lifecycle?

**Comment by Mike-E-angelo** [comment] 2022-09-06 14:46
Thank you very much @EdCharbeneau. 🙏  As for lifecycle, the first one appears to occur in the `OnAfterRenderAsync` event and the second occurs on the component dispose.  Unfortunately, that is all I can report at the moment.  If you are looking for further detail I can keep an eye out for it (and/or append telemetry) and see if I can get it for you.

**Comment by joepvtl** [comment] 2022-09-07 12:06
Hi,

We are also having the same exception as the first one. It some times occuress during the first render of the application. Probably because the JS BlazorSize module has not been loaded yet, but the blazor interop is already running?

```
System.Exception: Unhandled exception rendering component: Importing a module script failed.
undefined
at Microsoft.JSInterop.JSRuntime.<InvokeAsync>d__16`1[[Microsoft.JSInterop.IJSObjectReference, Microsoft.JSInterop, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].MoveNext()
at BlazorPro.BlazorSize.ResizeListener.Start()
at BlazorPro.BlazorSize.ResizeListener.<Subscribe>b__9_0()
```

**Comment by EdCharbeneau** [comment] 2022-09-08 18:02
Are you seeing this on Blazor Server or WASM,?

**Comment by joepvtl** [comment] 2022-09-08 18:59
Hi, we are experiencing this on WASM.

**Comment by Mike-E-angelo** [comment] 2022-09-09 07:10
For the DisposeAsync, that one looks like it's consistently occurring when I close the browser tab containing a page with the control loaded.

**Comment by Mike-E-angelo** [comment] 2022-10-06 11:45
FWIW I am also seeing the `Importing a module script failed.` in other parts of my application but again intermittent.  It's as if the script/file/resource fails to load.  

I think the reason why it occurs in BlazorSize more than others is that it is the first import to load on my page (one of the first components)

I saw #71 and see there's a reference to `UseStaticWebAssets` and am wondering if that may be a possible factor/mitigation?  From what I understand, however, that only works for applications not using `dotnet publish` (which as I understand it, occurs when I publish as an AppService).

**Comment by Mike-E-angelo** [comment] 2023-04-25 08:02
I've ignored these errors in production but indeed still see them all the time in development.  😭

**Comment by Mike-E-angelo** [comment] 2023-04-25 09:51
.NET7 here @joepvtl  :)

**Comment by joepvtl** [comment] 2023-04-25 09:59
@Mike-E-angelo do you have a reproducible scenario for the Import failed error?

**Comment by Mike-E-angelo** [comment] 2023-04-25 10:08
I wouldn't call it consistently reproducible @joepvtl but it happens quite a lot 😬  Normal usage + page loads/unloads invoke it quite a bit.  I just unhid `mediaquery` in my exception list and there's quite a bit over the past 6 hours alone

![image](https://user-images.githubusercontent.com/2931376/234244994-b53a800f-6bc7-4392-9897-8e054c47df5c.png)

**Comment by joepvtl** [comment] 2023-04-25 10:11
Yeah same here. It only happens for this package though, other packages are not having this issue. Do you know what happens when the error occurs? Does the end user see a error msg?

**Comment by Mike-E-angelo** [comment] 2023-04-25 10:13
As best as I can tell no they do not, at least I have personally not seen it, which is why I have hidden it in my list and (begrudgingly) swept it under the rug for the time being. 😞

**Comment by EdCharbeneau** [comment] 2023-04-25 14:50
I still haven't found a way of reproducing this. However, I do see the same error with Hot Reload's javascript when debugging in VS2022.

@joepvtl What other packages do you use? I would like to see if they're using lazy loading or plain JS references.

**Comment by EdCharbeneau** [comment] 2023-04-25 15:02
@Mike-E-angelo Can you confirm that this is happening in release/prod. I have had similar issues when debugging on localhost with the Hot Reload javascript dependencies.

**Comment by Mike-E-angelo** [comment] 2023-04-25 15:05
Indeed the screenshot provided above is from my production environment, @EdCharbeneau :)

**Comment by joepvtl** [comment] 2023-04-25 15:08
I also use MudBlazor, but I see that I have just included that script myself in the index.html. I don't see it ever occuring on my local environment. Only on the release/production one.

**Comment by EdCharbeneau** [comment] 2023-04-25 15:46
I'm trying to force the error so I can attempt to debug it. I removed the JavaScript module from the source code to see how what would happen. I get a different error.

Expected:
`Importing a module script failed.`

Actual:
`Failed to fetch dynamically imported module`

I need to understand what the difference is between the two errors now. If `Failed to fetch` means the module is not on disk, then what does `Importing a module script failed` actually mean is happening?

**Comment by SteveSandersonMS** [comment] 2023-04-25 16:03
Is the message browser-specific? If I search for `Importing a module script failed`, lots of the results talk about Safari specifically. Is it possible that other browsers use a different phrasing, such as `Failed to fetch dynamically imported module`?

Or can you repro the `Importing a module script failed` message on all browsers?

**Comment by EdCharbeneau** [comment] 2023-04-25 16:04
@Mike-E-angelo @joepvtl Can you verify which browser you're experiencing this error with?

**Comment by SteveSandersonMS** [comment] 2023-04-25 16:05
This issue: https://github.com/sveltejs/kit/issues/5208

... seems to imply the message is browser-specific, and that it can be triggered by the server returning a 500 instead of the JS module file. Is it possible the server, or some other proxy such as Cloudflare, is intermittently failing to return the content?

**Comment by Mike-E-angelo** [comment] 2023-04-25 16:23
So poking around here the original post had 2 exceptions.  The first one for importing a module script has actually not been reported in my logs since October of last year, so this appears addressed in my world. 👍

However, the second one is what I am seeing in my logs, with quite some frequency at that. 🤔

**Comment by EdCharbeneau** [comment] 2023-04-25 16:37
> So poking around here the original post had 2 exceptions. The first one for importing a module script has actually not been reported in my logs since October of last year, so this appears addressed in my world. 👍
> 
> However, the second one is what I am seeing in my logs, with quite some frequency at that. 🤔

Moving to a new issue https://github.com/EdCharbeneau/BlazorSize/issues/90

**Closed** 2023-04-25 16:43 UTC
